// Shared Tailwind class strings for the property-profile sub-components.
// These controls (inputs, save/cancel/delete/remove buttons, the card
// section, the photo frame) appear in more than one sub-component, so they
// live here to keep their appearance identical wherever they are used.
//
// Migrated 1:1 from the former PropertyProfile.module.css. Design tokens are
// referenced through the Tailwind utilities generated by the @theme block in
// app/globals.css (e.g. bg-ink, shadow-card, rounded-lg). Transitions use the
// arbitrary `[transition:...]` shorthand (underscores = spaces) — matching the
// sibling NewPropertyForm.tsx — so the timing (ease @ 0.15s) is identical to
// the original CSS. Note Tailwind v4 renders `-translate-y-px` via the CSS
// `translate` property, so the button-lift transition names `translate`.

// Card / section shell — used by the units section and the maintenance board
// wrapper (formerly .section).
export const sectionClass =
  'flex flex-col gap-4 bg-bg-surface border border-border rounded-lg p-6 shadow-card'

// Photo display — used by the profile card and the edit modal
// (formerly .photoFrame / .photo).
export const photoFrameClass =
  'w-full aspect-[4/3] rounded-md overflow-hidden border border-border bg-bg-sunken'
export const photoClass = 'w-full h-full object-cover block'

// Text input (formerly .input). `inputBase` omits the flex value so callers
// can pick their own (default flex-1, or flex-[2] for the wide city field).
export const inputBase =
  'min-w-0 px-3 py-2 text-base text-text-primary bg-input-bg border-[1.5px] border-input-border rounded-sm outline-none [transition:border-color_0.15s,box-shadow_0.15s] focus:border-input-border-focus focus:shadow-focus'
export const inputClass = `${inputBase} flex-1`

// Primary / secondary buttons (formerly .saveBtn / .cancelBtn).
export const saveBtnClass =
  'py-[0.45rem] px-4 text-[0.8125rem] font-semibold text-btn-text bg-ink rounded-pill cursor-pointer shadow-button whitespace-nowrap [transition:opacity_0.15s,translate_0.15s] enabled:hover:opacity-90 enabled:hover:-translate-y-px disabled:opacity-40 disabled:cursor-not-allowed disabled:shadow-none'
export const cancelBtnClass =
  'py-[0.45rem] px-3.5 text-[0.8125rem] font-medium text-text-secondary border-[1.5px] border-border rounded-pill cursor-pointer whitespace-nowrap [transition:color_0.15s] hover:text-text-primary'

// Destructive controls (formerly .deleteBtn / .removeBtn).
export const deleteBtnClass =
  'py-[0.35rem] px-3.5 text-xs font-medium text-danger border-[1.5px] border-transparent rounded-pill cursor-pointer opacity-70 [transition:opacity_0.15s,background-color_0.15s] hover:opacity-100 hover:bg-danger-bg'
export const removeBtnClass =
  'py-[0.2rem] px-2 text-[0.6875rem] text-text-muted cursor-pointer rounded-sm [transition:color_0.15s,background-color_0.15s] enabled:hover:text-danger enabled:hover:bg-danger-bg disabled:opacity-50 disabled:cursor-not-allowed'

// Inline form error text (formerly .error).
export const errorClass = 'text-xs text-danger'
